version: '3'

services:
  app:
    image: 'avgdemo:latest'
    ports:
      - '9000:8080'
    build:
      context: .
    container_name: app
    depends_on:
      - demo_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://demo_db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres

  demo_db:
    image: 'postgres:14'
    container_name: demo_db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
