version: '3'

services:

  demo_db:
    image: 'postgres:14'
    container_name: demo_db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    restart: unless-stopped

  demoapp:
    image: 'avgdima/avgdemo:latest'
    build:
      context: .
    container_name: demoapp
    expose:
      - '8080'
    depends_on:
      - demo_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://demo_db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
    restart: unless-stopped


  nginx:
    image: nginx:latest
    container_name: demo_proxy
    depends_on:
      - demoapp
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
