version: '3'

services:

  demo_db:
    image: 'postgres:14'
    container_name: demo_db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    restart: unless-stopped

  demoapp:
    image: 'avgdima/avgdemo:latest'
    build:
      context: .
    container_name: demoapp
    expose:
      - '8080'
    depends_on:
      - caddy
      - demo_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://demo_db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
    restart: unless-stopped

  caddy:
    image: caddy:2.7.4
    ports:
      - 80:80
      - 2019:2019
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile


  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    depends_on:
      - caddy
    ports:
      - "9090:9090"
    volumes:
      - ./metrics/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    restart: unless-stopped
    #    config mount doesn't work, folder structure has to be fixed
    volumes:
      - ./metrics/grafana:/var/lib/grafana
