name: Build and deploy

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build -x test
      - name: Cache artifact
        id: cache-artifact
        uses: actions/cache@v3
        with:
          path: |
            build/libs
            Dockerfile
          key: ${{ runner.os }}-cache
  build-docker-image:
    needs: 'build-gradle-project'
    runs-on: ubuntu-latest
    steps:
      - name: Restore cached artifact
        id: cache-artifact-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            build/libs
            Dockerfile
          key: ${{ runner.os }}-cache
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        run: |
          docker buildx build --platform linux/amd64 -t avgdima/avgdemo:${{ github.sha }} --push .
  deploy-k8s:
    needs: build-docker-image
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
      - name: Use context
        run: kubectl config use-context do-ams3-k8s-1-28-2-do-0-ams3-1700429081805
      - name: Replace image tag
        run: sed -i 's/_VERSION_/${{ github.sha }}/g' k8s/app-deployment.yaml
      - name: Deploy to K8s
        run: kubectl apply -f k8s/app-deployment.yaml -n avgdemo

          
