name: Build Gradle project

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build -x test
  build-docker-image:
    needs: 'build-gradle-project'
    runs-on: ubuntu-latest
    steps:
      - name: 'build docker image'
        run: docker build . -t avgdemo
