name: Build Gradle project

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            build/libs
            Dockerfile
  build-docker-image:
    needs: 'build-gradle-project'
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: 'build docker image'
        run: ls -a
